name: SonarCloud Code Inspection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze with SonarCloud
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=hhaidarr_basic-java-maven-main

      - name: Build Artifact (JAR)
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-jar
          path: target/*.jar


  deploy-to-staging:
    needs: sonarcloud
    runs-on: ubuntu-latest
    environment: staging 
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app-jar

      - name: Simulate Staging Deployment
        run: |
          echo "Menjalankan gerbang Continuous Delivery..."
          echo "File JAR berhasil diverifikasi dan siap dikirim ke lingkungan Staging!"


  deploy-to-production:
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app-jar

      - name: Deploy JAR to Production Server (Simulation)
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Menghubungkan ke server produksi melalui SSH ke $USER@$HOST..."
          echo "Mengirimkan file .jar ke direktori /var/www/java-apps/..."
          echo "Koneksi SSH ke Production Berhasil!"
          echo "Aplikasi Java diperbarui dan dijalankan otomatis tanpa intervensi manual!"